show_me_app/config/routes.rb
Rails.application.routes.draw do

	devise_for :users
	resources :projects


	root "static#home"

end

show_me_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

show_me_app/app/models/project.rb
class Project < ApplicationRecord
	
	has_attached_file :image

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :title, :description, presence: true

  has_many :tags
end

show_me_app/app/models/user.rb
class User < ApplicationRecord
	has_many :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	    :recoverable, :rememberable, :trackable, :validatable
end

show_me_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	#Sets up the parameters for divise user if it is the devise controller
	before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    	#Overides devise user controller to force in role, name and year parameters
        def configure_permitted_parameters
        	
            devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :role, :year, :password])
            devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :role, :year, :password, :current_password])
        end
end

show_me_app/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  #Index
  def index
    @users = User.all #Line changed
    @projects = if params[:term]
        Project.where('title LIKE ?', "%#{params[:term]}%").or(Project.where('collabarators LIKE ?', "%#{params[:term]}%")).or(Project.where('year LIKE ?', "%#{params[:term]}%"))
      else
        @projects = current_user.projects
      end
  end

  #Show
  def show
    @project = Project.find(params[:id])
    @users = User.all #Line changed
  end

  #New
  def new
    @project = current_user.projects.new
  end

  #Create
  def create
    new_project = current_user.projects.create(project_params)
    new_project.save
    redirect_to new_project
  end

  #Edit
  def edit
    @project = current_user.projects.find(params[:id])

  end

  #Update
  def update
    if current_user.role == "Admin"
      project = Project.find(params[:id])
      project.update(project_params)

    else 
      project = current_user.projects.find(params[:id])
      project.update(project_params)

    end
    redirect_to project
  end

  #Destroy
  def destroy
    if current_user.role == "Admin"
      Project.destroy(params[:id])

    else 
      current_user.projects.destroy(params[:id])

    end
    
    redirect_to projects_url
  end


  protected
  def project_params
    params.require(:project).permit(:title, :description, :live, :collabarators, :image, :css, :html, :javascript, :ruby, :rails, :term, :github, :year)

  end

end

show_me_app/app/controllers/static_controller.rb
class StaticController < ApplicationController

	def home
		@projects = Project.all
		@users = User.all #Line changed
		render template: "projects/index"
	end

end

show_me_app/app/helpers/application_helper.rb
module ApplicationHelper
end

show_me_app/app/helpers/projects_helper.rb
module ProjectsHelper
end

show_me_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Show Case</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <!-- Nav-Bar -->
    <div class="header-nav-bar">
      <div class="container-header">
        <!-- Sparta Logo embedded in Nav Bar -->
        <%= link_to(image_tag("sparta-global-logo.svg"), root_path) %>
        <!-- Checks to see if user is signed in or not and dynamically changes Nav Bar options -->
        <p>
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong> <br>
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
      </div>
    </div>
    <!-- Bootstrap's notices and alerts for well and ill requests -->
    <% if notice %>
      <p class="alert alert-success"> <%= notice %> </p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"> <%= alert %> </p>
    <% end %>

      <%= yield %>

  </body>
</html>

show_me_app/app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <h3><%= pluralize(@project.errors.count, 'error')%> prohibited this project from being saved</h3>

  <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%=msg%></li>
    <% end %>
  </ul>

<% end %>

<!-- Form for the project resource - used for creating and updating projects-->
<%= form_for(@project, multipart: true) do |f| %>

	  <%= f.label :title %>
	  <%= f.text_field :title %>

	  <%= f.label :description %>
	  <%= f.text_area :description, :id => "resize-texfield" %>

	  <%= f.label :collabarators %>
	  <%= f.text_field :collabarators %>

	  <%= f.label :github %>
	  <%= f.text_field :github %>

	  <%= f.label :year %>
	  <%= f.text_field :year %>

	  <div class="field">
	    <%= f.label :image %>
	    <%= f.file_field :image %>
	  </div>

	  <p><strong>Tags:</strong></p>
	  <ul id="tag-list">

	  		<li class="tag-item">
			<%= f.label "CSS" %>
		    <%= f.check_box(:css) %>
		    </li>

		    <li class="tag-item">
		    <%= f.label "HTML" %>
		    <%= f.check_box(:html) %>
		    </li>

		    <li class="tag-item">
		    <%= f.label "JavaScript" %>
		    <%= f.check_box(:javascript) %>
		    </li>

		    <li class="tag-item">
		    <%= f.label "Ruby" %>
		    <%= f.check_box(:ruby) %>
		    </li>

		    <li class="tag-item">
		    <%= f.label "Rails" %>
		    <%= f.check_box(:rails) %>
		    </li>

		</ul>

	  <%= f.submit :id => "submit" %>
  <% end %>

show_me_app/app/views/projects/_project.html.erb
<!-- Checks to see if a User is present and if it is, then checks to see if they're an admin and if projects are live -->
<% if current_user.present? %>

	<% if (current_user.role == "Admin") || (project.live == true) || (current_page?(projects_path)) %> <!-- will be true -->

		<!-- Rendering the project and relevant buttons and links -->
		<div class="col-xl-2 col-lg-2 col-md-4 col-sm-6">
			<div class="text">
				<img src="https://s3.eu-west-2.amazonaws.com/eng-2-project-2<%= project.image.path %>" width="500px" height="300px">
				<div id="project-text-container">
					<h4 id="title"><strong>Title: </strong><%= project.title %></h4>
					<br>
					<a class="a-link" href="<%= project.github %>" target="_blank">Github link</a>
					<p><strong>Description: </strong><%= project.description %></p>
					<p><strong>Collabarators: </strong><%= project.collabarators %></p>
					<p><strong>Year: </strong><%= project.year %></p>

					<div id="tag-container">
            
	             		<p><strong>Tags:</strong></p>
					  	<%= form_for(project) do |f| %>
						  	<ul id="tag-list">
						  		<li class="tag-item">
									<%= f.label "CSS" %>
								    <%= f.check_box(:css, :disabled => true) %>
							    </li>

							    <li class="tag-item">
							    <%= f.label "HTML" %>
							    <%= f.check_box(:html, :disabled => true) %>
							    </li>

							    <li class="tag-item">
							    <%= f.label "JavaScript" %>
							    <%= f.check_box(:javascript, :disabled => true) %>
							    </li>

							    <li class="tag-item">
							    <%= f.label "Ruby" %>
							    <%= f.check_box(:ruby, :disabled => true) %>
							    </li>

							    <li class="tag-item">
							    <%= f.label "Rails" %>
							    <%= f.check_box(:rails, :disabled => true) %>
							    </li>
						    </ul>
						    <p><strong>Uploaded by: </strong><%= @users.find(project.user_id).name %></p> <!-- Finds user by project user id -->
						<% end %>	
				  	</div>

				<% if current_page?(root_path) %>
					<%= link_to "Show Page", project_path(project), :class => "a-link" %>
				<% end %>

					<% if current_user.present? %>
						<!-- Only show edit link to the current user's project -->
						<% if current_user.id == project.user_id %>
							<%= link_to "Edit Page", edit_project_path(project), :class => "a-link" %>
						<% end %>
						<br>
						<!--- If user is admin -->
						<% if current_user.role == "Admin" %>
							<%= form_for(project) do |f| %>
								<%= f.label "Live" %>
						    <%= f.check_box(:live) %>
								<%= f.submit "Submit" %>
							<% end %>	
						<% end %>	
					<% end %>
					<br>
					<!-- Always show link to Home page, but only show delete if project belongs to user or if you're admin -->
				<% unless current_page?(root_path) || current_page?(projects_path)%>
				  <%= link_to "Home", root_path %> |
					  <% if current_user.present? %>
						<% if current_user.id == @project.user_id || current_user.role == "Admin" %>
							<%= link_to "Delete", @project, method: :delete, data: { confirm: "Are you sure?" } %>
						<% end %>
					<% end %>
				<% end %>
				</div>	
			</div>
		</div>
	<% end %>
<!-- If any User is NOT signed in and if projects are live then render all projects -->
<% elsif !current_user.present? && (project.live == true) %>
	<div class="col-xl-2 col-lg-2 col-md-2 col-sm-6 col-md-offset-2 col-lg-offset-2 col-sm-offset-2">
			<div class="text">
				<img src="https://s3.eu-west-2.amazonaws.com/eng-2-project-2<%= project.image.path %>" width="500px" height="300px">
				<div id="project-text-container">
					<p><strong>Title: </strong><%= project.title %></p>
					<a class="a-link" href="<%= project.github %>" target="_blank">Github link</a>
					<p><strong>Description: </strong><%= project.description %></p>
					<p><strong>Collabarators: </strong><%= project.collabarators %></p>
					<p><strong>Year: </strong><%= project.year %></p>

					 <div id="tag-container">

					  <p><strong>Tags:</strong></p>

					  	<%= form_for(project) do |f| %>
						  	<ul id="tag-list">
						  		<li class="tag-item">
									<%= f.label "CSS" %>
								    <%= f.check_box(:css, :disabled => true) %>
							    </li>

							    <li class="tag-item">
							    <%= f.label "HTML" %>
							    <%= f.check_box(:html, :disabled => true) %>
							    </li>

							    <li class="tag-item">
							    <%= f.label "JavaScript" %>
							    <%= f.check_box(:javascript, :disabled => true) %>
							    </li>

							    <li class="tag-item">
							    <%= f.label "Ruby" %>
							    <%= f.check_box(:ruby, :disabled => true) %>
							    </li>

							    <li class="tag-item">
							    <%= f.label "Rails" %>
							    <%= f.check_box(:rails, :disabled => true) %>
							    </li>
						    </ul>
						    <p><strong>Uploaded by: </strong><%= @users.find(project.user_id).name %></p> <!-- Finds user by project user id -->
						<% end %>
						<%= link_to "Show Page", project_path(project), :class => "a-link" %>

					  </div>
			</div>
		</div>
	</div>
<% end %>

show_me_app/app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<!-- Renders the form partial and allows the user to update the current project information -->
<%= render "form" %>

show_me_app/app/views/projects/index.html.erb
<!-- Homepage - root page -->
<% if current_page?(root_path) %>
	<h1>All Projects</h1>
<% else %>
<!-- If the current page is not the root, show the My Projects page -->
	<h1>My Projects</h1>
<% end %>

<!-- If User is not signed in don't show these links -->
<% if current_user.present? %>
	<%= link_to "Home", '/' %> |
	<%= link_to "New Project", new_project_path %> |
	<%= link_to "My Projects", projects_path %>
<% end %>

<br>
<%= form_tag(projects_path, method: :get) do %>
  <%= text_field_tag :term, nil, placeholder: "Search for title or collaborators or year created" %>
  <%= submit_tag 'Search', name: nil %>
<% end %>

<div class="container">
	<div class="row">
		<!-- Render the projects -->
		<%= render @projects %>
	</div>
</div>

show_me_app/app/views/projects/new.html.erb
<div class="login-block-for-login">
	<h1>New Project</h1>
	<!-- Render form which allows user to enter information to create a new project -->
	<%= render "form" %>
</div>

show_me_app/app/views/projects/show.html.erb
<h1>Project Show Page</h1>

<%= form_tag(projects_path, method: :get) do %>
  <%= text_field_tag :term, nil, placeholder: "Search for title or collaborators" %>
  <%= submit_tag 'Search', name: nil %>
<% end %>

<% if @project.live == false %>
	<p><strong> The project is not live, awaiting admin approval <strong></p>
<% end %>
<!-- Render the projects -->	
<%= render @project%>

show_me_app/app/views/tags/create.html.erb
<!-- Create Tags -->
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

show_me_app/app/views/tags/destroy.html.erb
<!-- Delete tags -->
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>